<template>
  <!-- NAV -->
  <nav class="bg-white border-b border-gray-200 sticky top-0 z-50 flex items-center px-8 h-16">
    <RouterLink to="/" class="text-xl font-black text-gray-900" style="letter-spacing: -0.5px;">
      Post<span class="text-blue-600">AI</span>
    </RouterLink>
  </nav>

  <main class="auth-main">

    <!-- LEFT: Branding panel -->
    <div class="auth-brand">
      <div class="auth-brand-inner">
        <div class="auth-badge">🇵🇭 BUILT FOR FILIPINO BUSINESSES</div>
        <h2 class="auth-brand-title">
          Stay active on Facebook.<br />
          <span class="text-yellow-400">Without the stress.</span>
        </h2>
        <p class="auth-brand-sub">
          PostAI creates branded posts in minutes — captions, images, and scheduling all in one place.
        </p>

        <div class="auth-benefits">
          <div class="auth-benefit"><span class="ab-icon">✓</span> 5 free posts to start</div>
          <div class="auth-benefit"><span class="ab-icon">✓</span> No design skills needed</div>
          <div class="auth-benefit"><span class="ab-icon">✓</span> Caption in Filipino, Taglish, or English</div>
          <div class="auth-benefit"><span class="ab-icon">✓</span> Auto-post to your Facebook Page</div>
        </div>

        <!-- Mini mockup -->
        <div class="auth-mockup">
          <div class="am-header">
            <div class="am-avatar">🌱</div>
            <div>
              <div class="am-name">Lola's Carinderia</div>
              <div class="am-time">Just now · 🌐</div>
            </div>
          </div>
          <p class="am-caption">Masarap na ulam, budget-friendly pa! 😋<br />Kain na sa Lola's Carinderia! ❤️</p>
          <div class="am-img">
            <div class="am-img-text">SARAP NA<br />ABOT-KAYA!</div>
            <div class="am-img-emoji">🍲</div>
          </div>
          <div class="am-badge">✦ Generated by PostAI</div>
        </div>
      </div>
    </div>

    <!-- RIGHT: Auth form -->
    <div class="auth-form-col">
      <div class="auth-card">

        <!-- Tabs -->
        <div class="auth-tabs">
          <button
            class="auth-tab"
            :class="{ active: activeTab === 'login' }"
            @click="switchTab('login')"
          >Log In</button>
          <button
            class="auth-tab"
            :class="{ active: activeTab === 'signup' }"
            @click="switchTab('signup')"
          >Sign Up</button>
        </div>

        <!-- ===== LOGIN FORM ===== -->
        <form v-if="activeTab === 'login'" @submit.prevent="handleLogin">
          <h1 class="auth-form-title">Welcome back!</h1>
          <p class="auth-form-sub">Log in to your PostAI account.</p>

          <div class="af-field">
            <label class="af-label">Email Address</label>
            <div class="af-input-wrap">
              <span class="af-icon">✉</span>
              <input v-model="login.email" type="email" class="af-input" placeholder="youremail@gmail.com" required />
            </div>
          </div>

          <div class="af-field">
            <label class="af-label">
              Password
              <a href="#" class="af-forgot">Forgot password?</a>
            </label>
            <div class="af-input-wrap">
              <span class="af-icon">🔒</span>
              <input
                v-model="login.password"
                :type="showLoginPw ? 'text' : 'password'"
                class="af-input"
                placeholder="••••••••"
                required
              />
              <button type="button" class="af-toggle-pw" @click="showLoginPw = !showLoginPw">
                {{ showLoginPw ? '🙈' : '👁' }}
              </button>
            </div>
          </div>

          <button type="submit" class="af-submit">Log In →</button>
          <p class="af-switch">Don't have an account? <a href="#" @click.prevent="switchTab('signup')">Sign up free</a></p>
        </form>

        <!-- ===== SIGNUP FORM ===== -->
        <form v-if="activeTab === 'signup'" @submit.prevent="handleSignup">
          <h1 class="auth-form-title">Create your account</h1>
          <p class="auth-form-sub">Get 5 free posts when you sign up. No credit card needed.</p>

          <!-- Step indicator -->
          <div class="signup-steps">
            <div class="ss-step" :class="stepClass(1)">1 Account</div>
            <div class="ss-divider">›</div>
            <div class="ss-step" :class="stepClass(2)">2 Business</div>
            <div class="ss-divider">›</div>
            <div class="ss-step" :class="stepClass(3)">3 Brand</div>
          </div>

          <!-- Step 1: Account details -->
          <div v-if="signupStep === 1">
            <div class="af-field">
              <label class="af-label">Your Name</label>
              <div class="af-input-wrap">
                <span class="af-icon">👤</span>
                <input v-model="signup.name" type="text" class="af-input" placeholder="Maria Santos" required />
              </div>
            </div>
            <div class="af-field">
              <label class="af-label">Email Address</label>
              <div class="af-input-wrap">
                <span class="af-icon">✉</span>
                <input v-model="signup.email" type="email" class="af-input" placeholder="youremail@gmail.com" required />
              </div>
            </div>
            <div class="af-field">
              <label class="af-label">Password</label>
              <div class="af-input-wrap">
                <span class="af-icon">🔒</span>
                <input
                  v-model="signup.password"
                  :type="showSignupPw ? 'text' : 'password'"
                  class="af-input"
                  placeholder="At least 8 characters"
                  required
                />
                <button type="button" class="af-toggle-pw" @click="showSignupPw = !showSignupPw">
                  {{ showSignupPw ? '🙈' : '👁' }}
                </button>
              </div>
            </div>
            <button type="button" class="af-submit" @click="signupNext">Continue →</button>
          </div>

          <!-- Step 2: Business info -->
          <div v-if="signupStep === 2">
            <div class="af-field">
              <label class="af-label">Business Name <span class="af-req">*</span></label>
              <div class="af-input-wrap">
                <span class="af-icon">🏪</span>
                <input v-model="signup.bizName" type="text" class="af-input" placeholder="Nanay's Carinderia" />
              </div>
            </div>
            <div class="af-field">
              <label class="af-label">Business Category <span class="af-req">*</span></label>
              <div class="su-cat-grid">
                <button
                  v-for="cat in categories"
                  :key="cat.val"
                  type="button"
                  class="su-cat"
                  :class="{ active: signup.category === cat.val }"
                  @click="signup.category = cat.val"
                >
                  <span>{{ cat.icon }}</span> {{ cat.label }}
                </button>
              </div>
            </div>
            <div class="af-field">
              <label class="af-label">Business Tagline <span class="af-hint">(optional)</span></label>
              <div class="af-input-wrap">
                <span class="af-icon">💬</span>
                <input v-model="signup.tagline" type="text" class="af-input" placeholder="e.g. Lutong bahay, araw-araw!" />
              </div>
            </div>
            <div class="su-nav-row">
              <button type="button" class="af-back" @click="signupStep = 1">← Back</button>
              <button type="button" class="af-submit af-submit--flex" @click="signupNext">Continue →</button>
            </div>
          </div>

          <!-- Step 3: Brand details -->
          <div v-if="signupStep === 3">
            <div class="af-field">
              <label class="af-label">Brand Tone</label>
              <div class="su-tone-grid">
                <button
                  v-for="tone in tones"
                  :key="tone.val"
                  type="button"
                  class="su-tone"
                  :class="{ active: signup.tone === tone.val }"
                  @click="signup.tone = tone.val"
                >
                  <span>{{ tone.icon }}</span>
                  <div>
                    <div class="su-tone-name">{{ tone.name }}</div>
                    <div class="su-tone-desc">{{ tone.desc }}</div>
                  </div>
                </button>
              </div>
            </div>
            <div class="af-field">
              <label class="af-label">Caption Language Preference</label>
              <div class="su-lang-grid">
                <button
                  v-for="lang in languages"
                  :key="lang.val"
                  type="button"
                  class="su-lang"
                  :class="{ active: signup.language === lang.val }"
                  @click="signup.language = lang.val"
                >
                  {{ lang.flag }} {{ lang.label }}
                </button>
              </div>
            </div>
            <div class="su-nav-row">
              <button type="button" class="af-back" @click="signupStep = 2">← Back</button>
              <button type="submit" class="af-submit af-submit--flex">Create Account →</button>
            </div>
          </div>

          <p class="af-switch">Already have an account? <a href="#" @click.prevent="switchTab('login')">Log in</a></p>
          <p class="af-terms">
            By signing up, you agree to our
            <a href="#">Terms of Service</a> and <a href="#">Privacy Policy</a>.
          </p>
        </form>

      </div>
    </div>
  </main>

  <!-- Toast -->
  <div class="toast" :class="[toast.show ? 'show' : '', toast.type ? `toast--${toast.type}` : '']">
    {{ toast.message }}
  </div>
</template>

<script setup>
import { ref, reactive } from 'vue';

const activeTab = ref('signup');
const signupStep = ref(1);
const showLoginPw = ref(false);
const showSignupPw = ref(false);

const login = reactive({ email: '', password: '' });
const signup = reactive({
  name: '', email: '', password: '',
  bizName: '', category: '', tagline: '',
  tone: 'Friendly', language: 'Filipino',
});

const toast = reactive({ show: false, message: '', type: '' });

const categories = [
  { val: 'Food & Carinderia',  icon: '🌱', label: 'Food & Carinderia' },
  { val: 'Salon & Beauty',     icon: '✂️', label: 'Salon & Beauty' },
  { val: 'Hardware Store',     icon: '🔧', label: 'Hardware Store' },
  { val: 'Resto-Bar',          icon: '🍻', label: 'Resto-Bar' },
  { val: 'Clothing & Fashion', icon: '👗', label: 'Clothing' },
  { val: 'Sari-Sari Store',    icon: '🏠', label: 'Sari-Sari Store' },
  { val: 'Other',              icon: '···', label: 'Other' },
];

const tones = [
  { val: 'Friendly',     icon: '😊', name: 'Friendly',     desc: 'Warm & approachable' },
  { val: 'Promotional',  icon: '📣', name: 'Promotional',  desc: 'Fun & sales-focused' },
  { val: 'Professional', icon: '💼', name: 'Professional', desc: 'Trustworthy & polished' },
  { val: 'Formal',       icon: '🏛️', name: 'Formal',       desc: 'Serious & authoritative' },
];

const languages = [
  { val: 'Filipino', flag: '🇵🇭', label: 'Filipino' },
  { val: 'Taglish',  flag: '🌏', label: 'Taglish' },
  { val: 'English',  flag: '🇬🇧', label: 'English' },
];

const showToast = (message, type = 'blue') => {
  toast.message = message;
  toast.type = type;
  toast.show = true;
  setTimeout(() => { toast.show = false; }, 3000);
};

const stepClass = (step) => {
  if (step < signupStep.value) return 'done';
  if (step === signupStep.value) return 'active';
  return '';
};

const switchTab = (tab) => {
  activeTab.value = tab;
  signupStep.value = 1;
};

const signupNext = () => {
  if (signupStep.value === 1) {
    if (!signup.name || !signup.email || !signup.password) {
      showToast('Please fill in all fields.', 'yellow'); return;
    }
    if (signup.password.length < 8) {
      showToast('Password must be at least 8 characters.', 'yellow'); return;
    }
  }
  if (signupStep.value === 2) {
    if (!signup.bizName || !signup.category) {
      showToast('Please enter your business name and category.', 'yellow'); return;
    }
  }
  signupStep.value++;
};

const handleLogin = () => {
  showToast('Logging you in…', 'blue');
};

const handleSignup = () => {
  showToast('Account created! Welcome to PostAI 🎉', 'green');
};
</script>

<style scoped>
/* ===== LAYOUT ===== */
.auth-main {
  display: grid;
  grid-template-columns: 1fr 1fr;
  min-height: calc(100vh - 64px);
}

/* ===== LEFT BRAND PANEL ===== */
.auth-brand {
  background: linear-gradient(160deg, #1e3a8a 0%, #1d4ed8 100%);
  padding: 48px;
  display: flex;
  align-items: center;
  justify-content: center;
  position: relative;
  overflow: hidden;
}
.auth-brand::before {
  content: '';
  position: absolute;
  inset: 0;
  background-image: radial-gradient(circle, rgba(255,255,255,0.03) 1px, transparent 1px);
  background-size: 30px 30px;
}
.auth-brand-inner { position: relative; z-index: 1; max-width: 440px; }

.auth-badge {
  display: inline-block;
  background: rgba(255,255,255,0.15);
  border: 1px solid rgba(255,255,255,0.25);
  color: #fff;
  font-size: 11px;
  font-weight: 700;
  letter-spacing: 1px;
  padding: 6px 14px;
  border-radius: 100px;
  margin-bottom: 20px;
}
.auth-brand-title {
  font-size: 32px;
  font-weight: 900;
  color: #fff;
  line-height: 1.2;
  margin-bottom: 12px;
}
.auth-brand-sub {
  font-size: 15px;
  color: rgba(255,255,255,0.75);
  line-height: 1.6;
  margin-bottom: 28px;
}

.auth-benefits { display: flex; flex-direction: column; gap: 10px; margin-bottom: 32px; }
.auth-benefit { display: flex; align-items: center; gap: 10px; font-size: 14px; color: rgba(255,255,255,0.9); }
.ab-icon {
  width: 20px; height: 20px; border-radius: 50%;
  background: #22c55e; color: #fff;
  display: flex; align-items: center; justify-content: center;
  font-size: 11px; font-weight: 700; flex-shrink: 0;
}

/* Mini mockup */
.auth-mockup {
  background: #fff;
  border-radius: 16px;
  padding: 16px;
  box-shadow: 0 12px 48px rgba(30,58,138,0.18);
}
.am-header { display: flex; align-items: center; gap: 10px; margin-bottom: 10px; }
.am-avatar {
  width: 36px; height: 36px; border-radius: 50%;
  background: #dbeafe;
  display: flex; align-items: center; justify-content: center;
  font-size: 18px;
}
.am-name { font-size: 13px; font-weight: 700; color: #0f172a; }
.am-time { font-size: 11px; color: #94a3b8; }
.am-caption { font-size: 13px; color: #0f172a; line-height: 1.5; margin-bottom: 10px; }
.am-img {
  background: linear-gradient(135deg, #1d4ed8, #3b82f6);
  border-radius: 10px; padding: 16px;
  display: flex; justify-content: space-between; align-items: center;
  margin-bottom: 10px;
}
.am-img-text { font-size: 14px; font-weight: 900; color: #fff; line-height: 1.3; }
.am-img-emoji { font-size: 28px; }
.am-badge { font-size: 11px; color: #2563eb; font-weight: 600; text-align: center; }

/* ===== RIGHT FORM PANEL ===== */
.auth-form-col {
  display: flex;
  align-items: center;
  justify-content: center;
  padding: 48px 32px;
  background: #f1f5f9;
}
.auth-card {
  width: 100%;
  max-width: 440px;
  background: #fff;
  border-radius: 20px;
  border: 1.5px solid #e2e8f0;
  padding: 36px;
  box-shadow: 0 4px 24px rgba(30,58,138,0.10);
}

/* Tabs */
.auth-tabs {
  display: flex;
  gap: 4px;
  background: #f1f5f9;
  border-radius: 10px;
  padding: 4px;
  margin-bottom: 28px;
}
.auth-tab {
  flex: 1; padding: 10px;
  border: none; border-radius: 8px;
  font-size: 14px; font-weight: 600; cursor: pointer;
  background: transparent; color: #475569;
  transition: all 0.2s;
}
.auth-tab.active {
  background: #fff;
  color: #0f172a;
  box-shadow: 0 2px 8px rgba(0,0,0,0.08);
}

/* Form typography */
.auth-form-title { font-size: 22px; font-weight: 800; color: #0f172a; margin-bottom: 4px; }
.auth-form-sub { font-size: 14px; color: #475569; margin-bottom: 24px; }

/* Fields */
.af-field { display: flex; flex-direction: column; gap: 6px; margin-bottom: 16px; }
.af-label {
  font-size: 13px; font-weight: 600; color: #0f172a;
  display: flex; justify-content: space-between; align-items: center;
}
.af-forgot { font-size: 12px; font-weight: 500; color: #2563eb; text-decoration: none; }
.af-req { color: #ef4444; }
.af-hint { font-size: 11px; color: #94a3b8; font-weight: 400; }
.af-input-wrap { position: relative; display: flex; align-items: center; }
.af-icon { position: absolute; left: 14px; font-size: 15px; color: #94a3b8; pointer-events: none; }
.af-input {
  width: 100%;
  padding: 12px 14px 12px 40px;
  border: 1.5px solid #e2e8f0;
  border-radius: 10px;
  font-size: 14px;
  font-family: inherit;
  color: #0f172a;
  background: #fff;
  transition: border-color 0.2s;
}
.af-input:focus {
  outline: none;
  border-color: #3b82f6;
  box-shadow: 0 0 0 3px #dbeafe;
}
.af-toggle-pw {
  position: absolute; right: 12px;
  background: none; border: none; cursor: pointer;
  font-size: 15px; padding: 4px;
}

/* Buttons */
.af-submit {
  width: 100%;
  padding: 13px;
  background: #2563eb;
  color: #fff;
  border: none;
  border-radius: 10px;
  font-size: 15px;
  font-weight: 700;
  cursor: pointer;
  transition: background 0.2s;
  margin-top: 4px;
}
.af-submit:hover { background: #1d4ed8; }
.af-submit--flex { width: auto; flex: 1; }
.af-back {
  padding: 13px 20px;
  background: #f1f5f9;
  color: #475569;
  border: 1.5px solid #e2e8f0;
  border-radius: 10px;
  font-size: 14px;
  font-weight: 600;
  cursor: pointer;
  transition: background 0.2s;
}
.af-back:hover { background: #e2e8f0; }
.su-nav-row { display: flex; gap: 10px; margin-top: 4px; }

.af-switch { text-align: center; font-size: 13px; color: #475569; margin-top: 20px; }
.af-terms { text-align: center; font-size: 11px; color: #94a3b8; margin-top: 10px; line-height: 1.5; }

/* Step indicator */
.signup-steps { display: flex; align-items: center; gap: 6px; margin-bottom: 24px; }
.ss-step {
  font-size: 12px; font-weight: 600; color: #94a3b8;
  padding: 4px 10px; border-radius: 100px;
  background: #f1f5f9; transition: all 0.2s;
}
.ss-step.active { background: #dbeafe; color: #1d4ed8; }
.ss-step.done { background: #dcfce7; color: #22c55e; }
.ss-divider { color: #94a3b8; font-size: 14px; }

/* Category grid */
.su-cat-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 8px; }
.su-cat {
  display: flex; align-items: center; gap: 8px;
  padding: 10px 12px;
  border: 1.5px solid #e2e8f0;
  border-radius: 10px;
  background: #fff;
  cursor: pointer;
  font-size: 13px; font-weight: 500; color: #0f172a;
  transition: all 0.2s; text-align: left;
}
.su-cat:hover { border-color: #3b82f6; background: #eff6ff; }
.su-cat.active { border-color: #2563eb; background: #eff6ff; box-shadow: 0 0 0 3px #dbeafe; }

/* Tone grid */
.su-tone-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 8px; }
.su-tone {
  display: flex; align-items: center; gap: 10px;
  padding: 12px;
  border: 1.5px solid #e2e8f0;
  border-radius: 10px;
  background: #fff;
  cursor: pointer; text-align: left; transition: all 0.2s;
}
.su-tone:hover { border-color: #3b82f6; background: #eff6ff; }
.su-tone.active { border-color: #2563eb; background: #eff6ff; box-shadow: 0 0 0 3px #dbeafe; }
.su-tone span { font-size: 20px; }
.su-tone-name { font-size: 13px; font-weight: 700; color: #0f172a; }
.su-tone-desc { font-size: 11px; color: #94a3b8; }

/* Language grid */
.su-lang-grid { display: flex; gap: 8px; flex-wrap: wrap; }
.su-lang {
  flex: 1; min-width: 100px;
  padding: 10px 12px;
  border: 1.5px solid #e2e8f0;
  border-radius: 10px;
  background: #fff;
  cursor: pointer;
  font-size: 13px; font-weight: 600; color: #0f172a;
  transition: all 0.2s;
}
.su-lang:hover { border-color: #3b82f6; background: #eff6ff; }
.su-lang.active { border-color: #2563eb; background: #eff6ff; box-shadow: 0 0 0 3px #dbeafe; }

/* Toast */
.toast {
  position: fixed;
  bottom: 28px;
  left: 50%;
  transform: translateX(-50%) translateY(20px);
  background: #1e293b;
  color: #fff;
  padding: 12px 24px;
  border-radius: 100px;
  font-size: 14px;
  font-weight: 600;
  opacity: 0;
  pointer-events: none;
  transition: opacity 0.3s, transform 0.3s;
  z-index: 999;
  white-space: nowrap;
}
.toast.show { opacity: 1; transform: translateX(-50%) translateY(0); }
.toast--green { border-left: 4px solid #22c55e; }
.toast--blue  { border-left: 4px solid #3b82f6; }
.toast--yellow { border-left: 4px solid #facc15; }

/* Responsive */
@media (max-width: 900px) {
  .auth-main { grid-template-columns: 1fr; }
  .auth-brand { display: none; }
  .auth-form-col { padding: 32px 16px; }
}
@media (max-width: 480px) {
  .auth-card { padding: 24px 20px; }
  .su-cat-grid { grid-template-columns: 1fr; }
  .su-tone-grid { grid-template-columns: 1fr; }
}
</style>
